# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Trans_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiDialogTrans(QtWidgets.QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)

    def setup_ui(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(405, 265)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(160, 220, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 220, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 210, 371, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 160, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 70, 60, 16))
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(30, 50, 361, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 111, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(110, 160, 181, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.comboBox_trans = QtWidgets.QComboBox(Dialog)
        self.comboBox_trans.setGeometry(QtCore.QRect(110, 70, 181, 31))
        self.comboBox_trans.setObjectName("comboBox")
        self.comboBox_2_trans = QtWidgets.QComboBox(Dialog)
        self.comboBox_2_trans.setGeometry(QtCore.QRect(110, 110, 181, 26))
        self.comboBox_2_trans.setObjectName("comboBox_2")

        self.retranslate_ui(Dialog)
        self.pushButton.clicked.connect(self.swip_swap)
        self.pushButton_2.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def set_categories(self, categories):
        for category in categories:
            self.comboBox_trans.addItem(category.name, category)
            self.comboBox_2_trans.addItem(category.name, category)

    def retranslate_ui(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Submit"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.label.setText(_translate("Dialog", "Amount"))
        self.label_2.setText(_translate("Dialog", "To"))
        self.label_3.setText(_translate("Dialog", "From"))
        self.label_4.setText(_translate("Dialog", "Transfer Money"))

    def swip_swap(self):
        amount = self.lineEdit.text()
        if amount == "":
            QtWidgets.QMessageBox.warning(None, "Error", "Please enter an amount.")
        else:
            try:
                amount = float(amount)
                if amount <= 0:
                    QtWidgets.QMessageBox.warning(None, "Error", "Amount must be a positive number.")
                else:
                    selected_drop = self.comboBox_trans.currentData()
                    from_cat = selected_drop if selected_drop is not None else None
                    selected_drop_two = self.comboBox_2_trans.currentData()
                    to_cat = selected_drop_two if selected_drop_two is not None else None
                    from_cat.transfer_money(amount, to_cat)
                    QtWidgets.QMessageBox.information(None, "Money Transfered Successfully", "Thank you! $"\
                                                      + str(amount) + "was successfully transferred from "\
                                                      + from_cat.name + " to " + to_cat.name)
                    self.lineEdit.clear()
                    #print(to_cat.wallet)
                    #print(from_cat.wallet)
            except ValueError:
                QtWidgets.QMessageBox.warning(None, "Error", "Invalid amount entered. Please enter a positive number.")


